export const STEP_ON = 'STEP_ON'
export const STEP_OFF = 'STEP_OFF'

export const TRANSPORT_SET_POSITION = 'TRANSPORT_SET_POSITION'
export const TRANSPORT_RESET_POSITION = 'TRANSPORT_RESET_POSITION'
export const TRANSPORT_NEXT_POSITION = 'TRANSPORT_NEXT_POSITION'
