export const STEP_ON = 'STEP_ON'
export const STEP_OFF = 'STEP_OFF'
export const STEP_ON_TRY = 'STEP_ON_TRY'
export const STEP_OFF_TRY = 'STEP_OFF_TRY'

export const TRANSPORT_STOP = 'TRANSPORT_STOP'
export const TRANSPORT_PLAY = 'TRANSPORT_PLAY'
export const TRANSPORT_PAUSE = 'TRANSPORT_PAUSE'
export const TRANSPORT_SET_POSITION = 'TRANSPORT_SET_POSITION'
export const TRANSPORT_RESET_POSITION = 'TRANSPORT_RESET_POSITION'
export const TRANSPORT_NEXT_POSITION = 'TRANSPORT_NEXT_POSITION'

export const AUTH_SIGN_IN_TRY = 'AUTH_SIGN_IN_TRY'
export const AUTH_SIGN_IN_SUCCESS = 'AUTH_SIGN_IN_SUCCESS'
export const AUTH_SIGN_OUT_TRY = 'AUTH_SIGN_OUT_TRY'
export const AUTH_SIGN_OUT_SUCCESS = 'AUTH_SIGN_OUT_SUCCESS'

export const PEOPLE_UPDATE = 'PEOPLE_UPDATE'
